//! TUI application state.
//!
//! Owns the per-session state model that the event loop and renderer
//! consume — message history, mode toggles, permission queue, status-bar
//! identity, perf stats, and bounded log buffer. Mutated only by
//! `crate::tui::events` handlers and read by `crate::tui::ui` renderers.

use crate::tui::PermissionDecision;
use serde_json::Value;
use std::collections::VecDeque;
use std::path::{Path, PathBuf};
use tokio::sync::oneshot;
extern crate arboard;

/// Controls how thorough/verbose the AI's responses are.
/// Injected as a hint prefix on every user message.
#[derive(Debug, Clone, PartialEq, Default)]
pub enum EffortLevel {
    /// Brief, direct responses.
    Quick,
    /// Standard depth — the default.
    #[default]
    Normal,
    /// Thorough, comprehensive responses.
    Thorough,
}

#[derive(Debug, Clone, PartialEq)]
pub enum Mode {
    Input,
    Scrolling,
    PermissionDialog,
    AskUserQuestion,
    HelpOverlay,
    /// Showing staged file changes for user approval before writing to disk.
    DiffReview,
}

#[derive(Debug, Clone)]
pub struct DisplayEntry {
    pub kind: EntryKind,
    pub content: String,
}

#[derive(Debug, Clone, PartialEq)]
pub enum EntryKind {
    UserMessage,
    AssistantMessage,
    ToolCall,
    ToolResult,
    ToolError,
    ImageAttachment,
    FileDiff,
    SystemInfo,
    Notice,
}

pub struct PendingPermission {
    pub tool_name: String,
    pub args: Value,
    /// Human-readable risk banner when the prompt fired due to the bash risk
    /// classifier. Rendered above the regular prompt; `None` for normal tools.
    pub reason: Option<String>,
    pub reply: oneshot::Sender<PermissionDecision>,
}

pub struct PendingQuestion {
    pub question: String,
    pub options: Vec<String>,
    pub reply: oneshot::Sender<String>,
}

const MAX_ENTRIES: usize = 1000;

pub struct App {
    pub mode: Mode,
    pub entries: Vec<DisplayEntry>,
    pub input: String,
    pub cursor: usize,
    pub streaming_partial: Option<String>,
    pub pending_permission: Option<PendingPermission>,
    pub pending_question: Option<PendingQuestion>,
    pub model: String,
    pub host: String,
    pub session_id: String,
    /// Identity-aware project label shown in the TUI chrome.
    pub project_display_name: String,
    pub agent_busy: bool,
    pub total_tokens: usize,
    pub should_quit: bool,
    /// Project-scoped config root (`~/.dm` in kernel, `<project>/.dm` in host).
    pub config_dir: PathBuf,
    /// Operator-scoped config root, always `~/.dm`; owns settings.json.
    pub global_config_dir: PathBuf,
    // Input history
    pub input_history: Vec<String>,
    pub history_pos: Option<usize>,
    pub history_scratch: String,
    // Vision: images attached for the next send (filename, base64_data)
    pub pending_images: Vec<(String, String)>,
    // Pending context (e.g. git diff) to prepend to the next user message
    pub pending_context: Option<String>,
    // Model list cache for /model Tab autocomplete
    pub available_models: Vec<String>,
    // Animation tick for spinner (incremented every 100ms by the event loop)
    pub tick: u64,
    // Name of the tool currently executing (None when idle)
    pub current_tool: Option<String>,
    // Model that dispatched the currently-executing tool (for status bar display)
    pub current_tool_model: Option<String>,
    // Session title generated by the background task (None until first turn completes)
    pub session_title: Option<String>,
    // MCP server status: (server_name, tool_count)
    pub mcp_servers: Vec<(String, usize)>,
    // Clipboard flash timestamp — set when a copy succeeds
    pub clipboard_flash: Option<std::time::Instant>,
    // Scroll state: absolute line from top (used in Scrolling mode)
    pub scroll_top: u16,
    // When true, viewport is pinned at scroll_top (Scrolling mode); false = auto-follow bottom
    pub scroll_locked: bool,
    // Cache written by render each frame so key handlers can clamp scroll values
    pub cached_total_lines: std::cell::Cell<u16>,
    pub cached_visible_height: std::cell::Cell<u16>,
    // Latest GPU stats from background poller (None if no GPU found)
    pub gpu_stats: Option<crate::gpu::GpuStats>,
    // Context window usage: (estimated_tokens_used, model_context_limit)
    // None until first ContextUsage event is received.
    pub ctx_usage: Option<(usize, usize)>,
    // Staged file changes awaiting user approval (populated by StagedChangeset event)
    pub staged_changes: Vec<crate::changeset::PendingChange>,
    /// Per-file decisions: None = undecided, Some(true) = accepted, Some(false) = rejected.
    pub diff_file_decisions: Vec<Option<bool>>,
    pub diff_review_idx: usize,
    pub diff_scroll: u16,
    /// True when connected to a background daemon (shows \[daemon\] in status bar).
    pub daemon_mode: bool,
    /// Live stdout/stderr lines from the currently-running bash tool (cleared on `ToolFinished`)
    pub current_tool_output: VecDeque<String>,
    /// Live / frozen inference performance stats (None before first streaming turn).
    pub perf: Option<PerfStats>,
    /// If true, tool output lines with file paths are wrapped in OSC 8 hyperlink escapes.
    pub hyperlinks: bool,
    /// Snapshot of display entries taken just before the last user turn, for `/undo`.
    pub undo_entries_snapshot: Option<Vec<DisplayEntry>>,
    /// Timestamp of the last Ctrl+C press (for double-press-to-quit).
    pub last_ctrl_c: Option<std::time::Instant>,
    /// Live snapshot of the running chain's state (None when no chain is active).
    pub chain_state: Option<crate::orchestrate::types::ChainState>,
    pub chain_event_rx:
        Option<tokio::sync::broadcast::Receiver<crate::daemon::protocol::DaemonEvent>>,
    /// Chain log lines for the detail pane (capped at 200).
    pub chain_log: Vec<String>,
    /// When true, show the expanded chain detail pane below the status bar.
    pub show_chain_pane: bool,
    /// Response depth hint injected on every user message (Normal = no hint).
    pub effort_level: EffortLevel,
    /// Files permanently prepended to every user message for the session lifetime.
    pub pinned_files: Vec<String>,
    /// When true, prepend a brevity hint to every message (like `/effort quick` but binary).
    pub brief_mode: bool,
    /// When true, write tools are blocked — model can only read and explore.
    pub plan_mode: bool,
    /// Cumulative token usage across all turns in this session.
    pub token_usage: TokenUsage,
    /// History of applied file changesets for `/undo-files` (newest last, max 10).
    pub file_undo_history: Vec<Vec<crate::changeset::PendingChange>>,
    /// Wall-clock start of the current agent turn (None when idle).
    pub turn_start: Option<std::time::Instant>,
    /// Play terminal bell when a turn completes (default: true).
    pub bell_on_complete: bool,
    /// Chronological activity log for /history (tool calls, file edits, etc.)
    pub activity_log: Vec<ActivityEntry>,
    /// None = idle. Some(_) = compaction is running; the status bar swaps
    /// `CTX N%` for `[compacting...]` while this is set. Stage is carried
    /// for future stage-aware UI — currently all stages render identically.
    pub is_compacting: Option<crate::compaction::CompactionStage>,
    /// Per-turn accumulator of file edits, flushed into a `SystemInfo` summary
    /// line when `TurnComplete` fires. Cleared after each flush regardless of
    /// summary emission (single-file turns suppress the summary but still
    /// reset the accumulator).
    pub turn_file_edits: Vec<crate::tui::agent::edit_summary::EditRecord>,
}

/// A single entry in the session activity log.
#[derive(Debug, Clone)]
pub struct ActivityEntry {
    pub timestamp: std::time::Instant,
    pub kind: ActivityKind,
    pub detail: String,
}

#[derive(Debug, Clone, PartialEq)]
pub enum ActivityKind {
    ToolCall,
    FileEdit,
    BashCommand,
    TurnComplete,
}

/// Performance metrics from the most recent (or in-progress) streaming turn.
#[derive(Debug, Clone)]
pub struct PerfStats {
    pub tok_per_sec: f32,
    pub ttft_ms: u64,
    #[allow(dead_code)]
    pub total_tokens: usize,
}

/// Cumulative token usage across all turns in a session.
#[derive(Debug, Clone, Default)]
pub struct TokenUsage {
    pub prompt_tokens: u64,
    pub completion_tokens: u64,
    pub turn_count: u32,
}

impl TokenUsage {
    pub fn total(&self) -> u64 {
        self.prompt_tokens + self.completion_tokens
    }

    pub fn record_turn(&mut self, prompt: u64, completion: u64) {
        self.prompt_tokens += prompt;
        self.completion_tokens += completion;
        self.turn_count += 1;
    }
}

impl App {
    pub fn new(
        model: String,
        host: String,
        session_id: String,
        config_dir: PathBuf,
        mcp_servers: Vec<(String, usize)>,
    ) -> Self {
        let input_history = load_history(&config_dir);
        let identity = crate::identity::load_for_cwd();
        App {
            mode: Mode::Input,
            entries: Vec::new(),
            input: String::new(),
            cursor: 0,
            streaming_partial: None,
            pending_permission: None,
            pending_question: None,
            model,
            host,
            session_id,
            project_display_name: identity.display_name().to_string(),
            agent_busy: false,
            total_tokens: 0,
            should_quit: false,
            global_config_dir: config_dir.clone(),
            config_dir,
            input_history,
            history_pos: None,
            history_scratch: String::new(),
            pending_images: Vec::new(),
            pending_context: None,
            available_models: Vec::new(),
            tick: 0,
            current_tool: None,
            current_tool_model: None,
            clipboard_flash: None,
            session_title: None,
            mcp_servers,
            scroll_top: 0,
            scroll_locked: false,
            cached_total_lines: std::cell::Cell::new(0),
            cached_visible_height: std::cell::Cell::new(24),
            gpu_stats: None,
            ctx_usage: None,
            staged_changes: Vec::new(),
            diff_file_decisions: Vec::new(),
            diff_review_idx: 0,
            diff_scroll: 0,
            daemon_mode: false,
            current_tool_output: VecDeque::new(),
            perf: None,
            hyperlinks: false,
            undo_entries_snapshot: None,
            last_ctrl_c: None,
            chain_state: None,
            chain_event_rx: None,
            chain_log: Vec::new(),
            show_chain_pane: false,
            effort_level: EffortLevel::Normal,
            pinned_files: Vec::new(),
            brief_mode: false,
            plan_mode: false,
            token_usage: TokenUsage::default(),
            file_undo_history: Vec::new(),
            turn_start: None,
            bell_on_complete: true,
            activity_log: Vec::new(),
            is_compacting: None,
            turn_file_edits: Vec::new(),
        }
    }

    pub fn push_chain_log(&mut self, line: String) {
        self.chain_log.push(line);
        if self.chain_log.len() > 200 {
            self.chain_log.remove(0);
        }
    }

    pub fn copy_flash_active(&self) -> bool {
        match self.clipboard_flash {
            Some(instant) => instant.elapsed() < std::time::Duration::from_millis(1500),
            None => false,
        }
    }

    pub fn copy_last_response(&mut self) {
        let text = self
            .entries
            .iter()
            .rev()
            .find(|e| e.kind == EntryKind::AssistantMessage)
            .map(|e| e.content.clone());
        if let Some(text) = text {
            // Silently ignore clipboard errors (headless CI)
            if let Ok(mut cb) = arboard::Clipboard::new() {
                let _ = cb.set_text(text);
            }
            self.clipboard_flash = Some(std::time::Instant::now());
        }
    }

    pub fn clear_images(&mut self) {
        self.pending_images.clear();
    }

    pub fn push_entry(&mut self, kind: EntryKind, content: String) {
        self.entries.push(DisplayEntry { kind, content });
        // Cap at MAX_ENTRIES; drop oldest when exceeded
        if self.entries.len() > MAX_ENTRIES {
            self.entries.drain(0..self.entries.len() - MAX_ENTRIES);
        }
        // total_tokens is set by TurnComplete from real Ollama eval_count — don't overwrite here
    }

    pub fn finalize_streaming(&mut self) {
        if let Some(partial) = self.streaming_partial.take() {
            if !partial.is_empty() {
                self.push_entry(EntryKind::AssistantMessage, partial);
            }
        }
        self.agent_busy = false;
        self.turn_start = None;
    }

    pub fn input_insert(&mut self, ch: char) {
        self.input.insert(self.cursor, ch);
        self.cursor += ch.len_utf8();
    }

    pub fn input_backspace(&mut self) {
        if self.cursor > 0 {
            let prev = self.input[..self.cursor]
                .char_indices()
                .last()
                .map_or(0, |(i, _)| i);
            self.input.drain(prev..self.cursor);
            self.cursor = prev;
        }
    }

    pub fn input_delete_forward(&mut self) {
        if self.cursor < self.input.len() {
            if let Some(c) = self.input[self.cursor..].chars().next() {
                self.input.drain(self.cursor..self.cursor + c.len_utf8());
            }
        }
    }

    /// Ctrl+A / Home: move cursor to start of line.
    pub fn input_move_start(&mut self) {
        self.cursor = 0;
    }

    /// Ctrl+E / End: move cursor to end of line.
    pub fn input_move_end(&mut self) {
        self.cursor = self.input.len();
    }

    /// Ctrl+K: kill from cursor to end of line.
    pub fn input_kill_to_end(&mut self) {
        self.input.truncate(self.cursor);
    }

    /// Ctrl+W: delete word backward (stop at whitespace boundary).
    pub fn input_delete_word_back(&mut self) {
        if self.cursor == 0 {
            return;
        }
        let bytes = self.input.as_bytes();
        let mut pos = self.cursor;
        while pos > 0 && bytes[pos - 1] == b' ' {
            pos -= 1;
        }
        while pos > 0 && bytes[pos - 1] != b' ' {
            pos -= 1;
        }
        self.input.drain(pos..self.cursor);
        self.cursor = pos;
    }

    /// Ctrl+Right / Alt+F: move cursor forward one word.
    pub fn input_move_word_forward(&mut self) {
        let bytes = self.input.as_bytes();
        let len = self.input.len();
        let mut pos = self.cursor;
        while pos < len && bytes[pos] != b' ' {
            pos += 1;
        }
        while pos < len && bytes[pos] == b' ' {
            pos += 1;
        }
        self.cursor = pos;
    }

    /// Ctrl+Left / Alt+B: move cursor backward one word.
    pub fn input_move_word_back(&mut self) {
        if self.cursor == 0 {
            return;
        }
        let bytes = self.input.as_bytes();
        let mut pos = self.cursor;
        while pos > 0 && bytes[pos - 1] == b' ' {
            pos -= 1;
        }
        while pos > 0 && bytes[pos - 1] != b' ' {
            pos -= 1;
        }
        self.cursor = pos;
    }

    pub fn take_input(&mut self) -> String {
        let text = self.input.clone();
        self.input.clear();
        self.cursor = 0;
        text
    }

    /// Push a line to input history (skips duplicates of the most recent entry).
    pub fn push_history(&mut self, text: String) {
        if self.input_history.last().map(|s| s.as_str()) != Some(text.as_str()) {
            self.input_history.push(text.clone());
            append_history(&self.config_dir, &text);
        }
        self.history_pos = None;
    }

    /// Move backward through history (older entries).
    pub fn history_prev(&mut self) {
        if self.input_history.is_empty() {
            return;
        }
        let new_pos = match self.history_pos {
            None => {
                self.history_scratch = self.input.clone();
                self.input_history.len() - 1
            }
            Some(0) => 0,
            Some(p) => p - 1,
        };
        self.history_pos = Some(new_pos);
        self.input = self.input_history[new_pos].clone();
        self.cursor = self.input.len();
    }

    /// Move forward through history (newer entries, then back to scratch).
    pub fn history_next(&mut self) {
        match self.history_pos {
            None => {}
            Some(p) if p + 1 >= self.input_history.len() => {
                self.history_pos = None;
                self.input = self.history_scratch.clone();
                self.cursor = self.input.len();
            }
            Some(p) => {
                self.history_pos = Some(p + 1);
                self.input = self.input_history[p + 1].clone();
                self.cursor = self.input.len();
            }
        }
    }
}

fn history_path(config_dir: &Path) -> PathBuf {
    config_dir.join("history")
}

fn load_history(config_dir: &Path) -> Vec<String> {
    let path = history_path(config_dir);
    match std::fs::read_to_string(&path) {
        Ok(content) => content
            .lines()
            .filter(|l| !l.is_empty())
            .map(|l| l.to_string())
            .collect(),
        Err(_) => Vec::new(),
    }
}

fn append_history(config_dir: &Path, line: &str) {
    let path = history_path(config_dir);
    if let Some(parent) = path.parent() {
        let _ = std::fs::create_dir_all(parent);
    }
    use std::io::Write;
    if let Ok(mut f) = std::fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&path)
    {
        let _ = writeln!(f, "{}", line);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn test_app() -> (App, TempDir) {
        let dir = TempDir::new().unwrap();
        let app = App::new(
            "model".to_string(),
            "localhost".to_string(),
            "test-id".to_string(),
            dir.path().to_path_buf(),
            vec![],
        );
        (app, dir)
    }

    #[test]
    fn ctrl_k_kills_to_end() {
        let (mut app, _dir) = test_app();
        app.input = "hello world".to_string();
        app.cursor = 5;
        app.input_kill_to_end();
        assert_eq!(app.input, "hello");
        assert_eq!(app.cursor, 5);
    }

    #[test]
    fn ctrl_w_deletes_word_back() {
        let (mut app, _dir) = test_app();
        app.input = "hello world".to_string();
        app.cursor = 11;
        app.input_delete_word_back();
        assert_eq!(app.input, "hello ");
        assert_eq!(app.cursor, 6);
    }

    #[test]
    fn word_forward_moves_past_word_and_space() {
        let (mut app, _dir) = test_app();
        app.input = "hello world".to_string();
        app.cursor = 0;
        app.input_move_word_forward();
        assert_eq!(app.cursor, 6); // past "hello" and the space
    }

    #[test]
    fn word_back_moves_to_word_start() {
        let (mut app, _dir) = test_app();
        app.input = "hello world".to_string();
        app.cursor = 11;
        app.input_move_word_back();
        assert_eq!(app.cursor, 6); // start of "world"
    }

    #[test]
    fn move_start_and_end() {
        let (mut app, _dir) = test_app();
        app.input = "hello".to_string();
        app.cursor = 3;
        app.input_move_start();
        assert_eq!(app.cursor, 0);
        app.input_move_end();
        assert_eq!(app.cursor, 5);
    }

    #[test]
    fn ctrl_w_noop_at_start() {
        let (mut app, _dir) = test_app();
        app.input = "hello".to_string();
        app.cursor = 0;
        app.input_delete_word_back();
        assert_eq!(app.input, "hello");
        assert_eq!(app.cursor, 0);
    }

    // ── PerfStats tests ───────────────────────────────────────────────────────

    #[test]
    fn perf_starts_as_none() {
        let (app, _dir) = test_app();
        assert!(app.perf.is_none(), "perf should be None on init");
    }

    #[test]
    fn perf_set_clears_on_new_turn() {
        let (mut app, _dir) = test_app();
        app.perf = Some(PerfStats {
            tok_per_sec: 12.0,
            ttft_ms: 300,
            total_tokens: 200,
        });
        // Simulate what input.rs does when a new turn begins
        app.perf = None;
        assert!(app.perf.is_none());
    }

    #[test]
    fn perf_frozen_after_turn_complete() {
        let (mut app, _dir) = test_app();
        // Populate during streaming
        app.perf = Some(PerfStats {
            tok_per_sec: 15.0,
            ttft_ms: 250,
            total_tokens: 500,
        });
        // TurnComplete arrives — nothing clears perf, it stays frozen
        // (clearing only happens on the NEXT turn start)
        assert!(app.perf.is_some());
        let p = app.perf.as_ref().unwrap();
        assert!((p.tok_per_sec - 15.0).abs() < 0.01);
        assert_eq!(p.ttft_ms, 250);
        assert_eq!(p.total_tokens, 500);
    }

    #[test]
    fn tok_per_sec_calculation() {
        // 100 tokens over 5.0 seconds → 20.0 tok/s
        let token_count: usize = 100;
        let elapsed_secs: f32 = 5.0;
        let tps = token_count as f32 / elapsed_secs;
        assert!((tps - 20.0).abs() < 0.01);
    }

    #[test]
    fn ttft_is_time_to_first_token() {
        // We can't go back in time in tests, so verify the constant relationship:
        // ttft_ms represents the elapsed milliseconds until the first token arrived.
        let fake_ttft_ms: u64 = 340;
        assert_eq!(fake_ttft_ms, 340);
    }

    #[test]
    fn perf_debounce_constant_is_250ms() {
        // Verify the constant is in range — unit tests can't easily mock time,
        // but we confirm the configured threshold is correct
        assert_eq!(crate::tui::agent::turn::PERF_DEBOUNCE_MS, 250);
    }

    #[test]
    fn perf_color_threshold_low_is_yellow() {
        // tok/s < 5 → yellow (mirrors the ui.rs logic)
        let tok_per_sec: f32 = 3.5;
        let is_yellow = tok_per_sec < 5.0;
        assert!(is_yellow, "slow inference should be yellow");
    }

    #[test]
    fn perf_color_threshold_high_is_green() {
        let tok_per_sec: f32 = 12.4;
        let is_green = tok_per_sec >= 5.0;
        assert!(is_green, "fast inference should be green");
    }

    // ── Status bar layout tests ───────────────────────────────────────────────

    fn make_app() -> App {
        App::new(
            "gemma4:26b".into(),
            "localhost:11434".into(),
            "test-session-id".into(),
            std::path::PathBuf::from("/tmp/dm-test"),
            vec![],
        )
    }

    #[test]
    fn status_bar_hides_line2_when_no_perf_no_gpu() {
        let app = make_app();
        // No perf, no gpu_stats, no ctx_usage → line 2 should not appear
        assert!(app.perf.is_none());
        assert!(app.gpu_stats.is_none());
        assert!(app.ctx_usage.is_none());
        // has_status_line2 logic: false when all three are None
        let has_line2 = app.perf.is_some() || app.ctx_usage.is_some() || app.gpu_stats.is_some();
        assert!(!has_line2, "line 2 should be hidden on fresh app");
    }

    #[test]
    fn status_bar_shows_line2_with_perf() {
        let mut app = make_app();
        app.perf = Some(PerfStats {
            tok_per_sec: 12.4,
            ttft_ms: 340,
            total_tokens: 500,
        });
        let has_line2 = app.perf.is_some() || app.ctx_usage.is_some() || app.gpu_stats.is_some();
        assert!(has_line2, "line 2 should appear when perf data is present");
    }

    #[test]
    fn status_bar_shows_routed_model_when_differs() {
        let mut app = make_app();
        app.current_tool_model = Some("llama3.2:3b".into());
        // current_tool_model differs from app.model ("gemma4:26b") → routed indicator visible
        let routed = app
            .current_tool_model
            .as_deref()
            .filter(|m| *m != app.model.as_str());
        assert_eq!(routed, Some("llama3.2:3b"));
    }

    // ── History navigation tests ──────────────────────────────────────────────

    fn app_with_history(entries: &[&str]) -> App {
        let mut app = make_app();
        for e in entries {
            app.input_history.push(e.to_string());
        }
        app
    }

    #[test]
    fn push_history_appends_new_entry() {
        let (mut app, _dir) = test_app();
        app.push_history("first".to_string());
        app.push_history("second".to_string());
        assert_eq!(app.input_history.len(), 2);
        assert_eq!(app.input_history[0], "first");
        assert_eq!(app.input_history[1], "second");
    }

    #[test]
    fn push_history_deduplicates_consecutive_identical() {
        let (mut app, _dir) = test_app();
        app.push_history("same".to_string());
        app.push_history("same".to_string()); // duplicate — should not append
        assert_eq!(app.input_history.len(), 1);
    }

    #[test]
    fn push_history_allows_non_consecutive_duplicate() {
        let (mut app, _dir) = test_app();
        app.push_history("a".to_string());
        app.push_history("b".to_string());
        app.push_history("a".to_string()); // not consecutive — should append
        assert_eq!(app.input_history.len(), 3);
    }

    #[test]
    fn push_history_resets_history_pos() {
        let (mut app, _dir) = test_app();
        app.push_history("old".to_string());
        app.history_prev(); // sets history_pos to Some(0)
        assert!(app.history_pos.is_some());
        app.push_history("new".to_string()); // should reset pos
        assert!(app.history_pos.is_none());
    }

    #[test]
    fn history_prev_on_empty_is_noop() {
        let (mut app, _dir) = test_app();
        app.input = "typing".to_string();
        app.history_prev();
        assert_eq!(app.input, "typing"); // unchanged
        assert!(app.history_pos.is_none());
    }

    #[test]
    fn history_prev_saves_scratch_on_first_call() {
        let mut app = app_with_history(&["cmd1", "cmd2"]);
        app.input = "in-progress".to_string();
        app.history_prev();
        assert_eq!(app.history_scratch, "in-progress");
        assert_eq!(app.input, "cmd2"); // most recent entry
        assert_eq!(app.history_pos, Some(1));
    }

    #[test]
    fn history_prev_twice_goes_further_back() {
        let mut app = app_with_history(&["oldest", "middle", "newest"]);
        app.history_prev(); // → newest (index 2)
        app.history_prev(); // → middle (index 1)
        assert_eq!(app.input, "middle");
        assert_eq!(app.history_pos, Some(1));
    }

    #[test]
    fn history_prev_clamps_at_oldest_entry() {
        let mut app = app_with_history(&["only"]);
        app.history_prev(); // → index 0
        app.history_prev(); // should stay at 0, not underflow
        assert_eq!(app.history_pos, Some(0));
        assert_eq!(app.input, "only");
    }

    #[test]
    fn history_next_without_prev_is_noop() {
        let mut app = app_with_history(&["cmd"]);
        app.input = "current".to_string();
        app.history_next(); // history_pos is None → noop
        assert_eq!(app.input, "current");
        assert!(app.history_pos.is_none());
    }

    #[test]
    fn history_next_restores_scratch_when_at_newest() {
        let mut app = app_with_history(&["old"]);
        app.input = "scratch".to_string();
        app.history_prev(); // go back to "old"
        app.history_next(); // go forward → back to scratch
        assert_eq!(app.input, "scratch");
        assert!(app.history_pos.is_none());
    }

    #[test]
    fn history_prev_and_next_round_trip() {
        let mut app = app_with_history(&["a", "b", "c"]);
        app.input = "original".to_string();
        app.history_prev(); // → "c"
        app.history_prev(); // → "b"
        app.history_next(); // → "c"
        app.history_next(); // → scratch "original"
        assert_eq!(app.input, "original");
        assert!(app.history_pos.is_none());
    }

    #[test]
    fn history_cursor_set_to_end_of_entry() {
        let mut app = app_with_history(&["hello"]);
        app.cursor = 0;
        app.history_prev();
        assert_eq!(app.cursor, "hello".len()); // cursor placed at end
    }

    #[test]
    fn status_bar_truncates_session_title_at_30_chars() {
        let long = "A very long session title that exceeds thirty chars";
        let truncated = if long.chars().count() > 30 {
            format!("{}…", long.chars().take(30).collect::<String>())
        } else {
            long.to_string()
        };
        // char count: 30 display chars + 1 ellipsis = 31
        assert_eq!(
            truncated.chars().count(),
            31,
            "truncated+ellipsis should be 31 display chars"
        );
        assert!(truncated.ends_with('…'));
    }

    #[test]
    fn token_usage_starts_at_zero() {
        let usage = TokenUsage::default();
        assert_eq!(usage.prompt_tokens, 0);
        assert_eq!(usage.completion_tokens, 0);
        assert_eq!(usage.turn_count, 0);
        assert_eq!(usage.total(), 0);
    }

    #[test]
    fn token_usage_total() {
        let usage = TokenUsage {
            prompt_tokens: 300,
            completion_tokens: 200,
            ..Default::default()
        };
        assert_eq!(usage.total(), 500);
    }

    #[test]
    fn file_undo_history_caps_at_10() {
        let mut history: Vec<Vec<crate::changeset::PendingChange>> = Vec::new();
        for _ in 0..12 {
            history.push(vec![crate::changeset::make_change(
                std::path::PathBuf::from("test.rs"),
                "old",
                "new",
            )]);
            if history.len() > 10 {
                history.remove(0);
            }
        }
        assert_eq!(history.len(), 10);
    }

    #[test]
    fn token_usage_accumulates() {
        let mut usage = TokenUsage::default();
        usage.record_turn(100, 50);
        usage.record_turn(200, 80);
        usage.record_turn(150, 70);
        assert_eq!(usage.prompt_tokens, 450);
        assert_eq!(usage.completion_tokens, 200);
        assert_eq!(usage.turn_count, 3);
        assert_eq!(usage.total(), 650);
    }

    #[test]
    fn delete_forward_removes_char_at_cursor() {
        let mut app = App::new(
            "gemma4:26b".into(),
            "localhost:11434".into(),
            "test-session".into(),
            std::path::PathBuf::from("/tmp"),
            vec![],
        );
        app.input = "hello".to_string();
        app.cursor = 2;
        app.input_delete_forward();
        assert_eq!(app.input, "helo");
        assert_eq!(app.cursor, 2);
    }

    #[test]
    fn delete_forward_at_end_is_noop() {
        let mut app = App::new(
            "gemma4:26b".into(),
            "localhost:11434".into(),
            "test-session".into(),
            std::path::PathBuf::from("/tmp"),
            vec![],
        );
        app.input = "hi".to_string();
        app.cursor = 2;
        app.input_delete_forward();
        assert_eq!(app.input, "hi");
        assert_eq!(app.cursor, 2);
    }
}
